// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DSS.Data.Models;

public partial class CompanyInformation
{
    public int CompanyId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Hotline { get; set; }

    public string Address { get; set; }

    public bool Status { get; set; }
}