// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DSS.Data.Models;

public partial class ExtraDiamond
{
    public long ExtraDiamondId { get; set; }

    public string Name { get; set; }

    public string Title { get; set; }

    public int Quantity { get; set; }

    public long Price { get; set; }

    public bool Status { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}