// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DSS.Data.Models;

public partial class MainDiamond
{
    public long MainDiamondId { get; set; }

    public string Name { get; set; }

    public string Origin { get; set; }

    public short CaraWeight { get; set; }

    public string Clarity { get; set; }

    public string Color { get; set; }

    public string Describe { get; set; }

    public long Quantity { get; set; }

    public long Cut { get; set; }

    public decimal Price { get; set; }

    public bool Status { get; set; }
}