// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DSS.Data.Models;

public partial class Order
{
    public long OrderId { get; set; }

    public long CustomerId { get; set; }

    public long OrderDate { get; set; }

    public decimal TotalAmount { get; set; }

    public string PaymentMethod { get; set; }

    public string PaymentStatus { get; set; }
}