// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DSS.Data.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public string Name { get; set; }

    public int MainDiamondId { get; set; }

    public int NumberExDiamond { get; set; }

    public int DiamondShellId { get; set; }

    public int Quantity { get; set; }

    public int Size { get; set; }

    public bool Status { get; set; }

    public double Amount { get; set; }

    public double Fee { get; set; }

    public double TotalAmount { get; set; }

    public virtual DiamondShell DiamondShell { get; set; }

    public virtual MainDiamond MainDiamond { get; set; }

    public virtual ExtraDiamond NumberExDiamondNavigation { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}